[build]
target = "xtensa-esp32-espidf"

[target.xtensa-esp32-espidf]
linker = "ldproxy"
# Baud rate may need to be adjusted for different devices / connections
runner = "espflash flash --baud 691200 --monitor"
# Extending time_t for ESP IDF 5: https://github.com/esp-rs/rust/issues/110
rustflags = [ "--cfg",  "espidf_time64"]

[unstable]
build-std = ["std", "panic_abort"]

[env]
MCU="esp32"
ESP_IDF_VERSION = "v5.1.1"

